/* eslint-disable @typescript-eslint/no-unnecessary-type-assertion */
import fs from 'node:fs';
import { getOptions } from '../lib/config/options';

const options = getOptions();

describe('documentation', () => {
  describe('website-documentation', () => {
    describe('configuration-options', () => {
      const doc = fs.readFileSync(
        'docs/usage/configuration-options.md',
        'utf8'
      );

      const headers = doc
        .match(/\n## (.*?)\n/g)
        ?.map((match) => match.substring(4, match.length - 1));

      const expectedOptions = options
        .filter((option) => !option.globalOnly)
        .filter((option) => !option.parent)
        .filter((option) => !option.autogenerated)
        .map((option) => option.name)
        .sort();

      it('has doc headers sorted alphabetically', () => {
        expect(headers).toEqual([...headers!].sort());
      });

      it('has headers for every required option', () => {
        expect(headers).toEqual(expectedOptions);
      });

      const subHeaders = doc
        .match(/\n### (.*?)\n/g)
        ?.map((match) => match.substring(5, match.length - 1));
      subHeaders!.sort();
      const expectedSubOptions = options
        .filter((option) => option.stage !== 'global')
        .filter((option) => !option.globalOnly)
        .filter((option) => option.parent)
        .map((option) => option.name)
        .sort();
      expectedSubOptions.sort();

      it('has headers for every required sub-option', () => {
        expect(subHeaders).toEqual(expectedSubOptions);
      });
    });

    describe('self-hosted-configuration', () => {
      const doc = fs.readFileSync(
        'docs/usage/self-hosted-configuration.md',
        'utf8'
      );

      const headers = doc
        .match(/\n## (.*?)\n/g)
        ?.map((match) => match.substring(4, match.length - 1));

      const expectedOptions = options
        .filter((option) => !!option.globalOnly)
        .map((option) => option.name)
        .sort();

      it('has headers sorted alphabetically', () => {
        expect(headers).toEqual([...headers!].sort());
      });

      it('has headers for every required option', () => {
        expect(headers).toEqual(expectedOptions);
      });
    });
  });
});
