pod 'a'
pod 'a/sub'
pod 'b', '1.2.3'
pod 'c', "1.2.3"
pod 'd', :path => '~/Documents/Alamofire'
pod 'e', :git => 'e.git'
pod 'f', :git => 'f.git', :branch => 'dev'
pod 'g', :git => 'g.git', :tag => '3.2.1'
