# renovate: datasource=docker depName=node versioning=docker
ARG NODE_VERSION=18

FROM node:${NODE_VERSION}

# renovate: datasource=npm depName=pnpm
ENV PNPM_VERSION="7.25.1"

# renovate: datasource=npm depName=yarn
ARG YARN_VERSION='3.3.1'
