import { MinMaxSatisfyingSampleElem, NewValueTestConfig } from './common';
import { sample as npmSample } from './npm.data';
import { sample as pep440Sample } from './pep440.data';

const getNewValueTestCases: NewValueTestConfig[] = [
  {
    title: 'bumps exact',
    currentValue: '1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '1.1.0',
  },
  {
    title: 'bumps exact',
    currentValue: '   1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '1.1.0',
  },
  {
    title: 'bumps exact',
    currentValue: '1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '1.1.0',
  },
  {
    title: 'bumps equals',
    currentValue: '=1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps equals',
    currentValue: '=  1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps equals space',
    currentValue: '= 1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps equals space',
    currentValue: '  = 1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps equals space',
    currentValue: '  =   1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps equals space',
    currentValue: '=    1.0.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps short caret to same',
    currentValue: '^1.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.0.7',
    expectedValue: '^1.0',
  },
  {
    title: 'replaces caret with newer',
    currentValue: '^1.0.0',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '2.0.7',
    expectedValue: '^2.0.0',
  },
  {
    title: 'replaces naked version',
    currentValue: '1.0.0',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '2.0.7',
    expectedValue: '2.0.7',
  },
  {
    title: 'replaces with version range',
    currentValue: '1.0.0',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '^2.0.7',
    expectedValue: '^2.0.7',
  },
  {
    title: 'bumps naked caret',
    currentValue: '^1',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '2.1.7',
    expectedValue: '^2',
  },
  {
    title: 'bumps naked tilde',
    currentValue: '~1',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.7',
    expectedValue: '~1',
  },
  {
    title: 'bumps naked major',
    currentValue: '5',
    rangeStrategy: 'bump',
    fromVersion: '5.0.0',
    toVersion: '5.1.7',
    expectedValue: '5',
  },
  {
    title: 'bumps naked major',
    currentValue: '5',
    rangeStrategy: 'bump',
    fromVersion: '5.0.0',
    toVersion: '6.1.7',
    expectedValue: '6',
  },
  {
    title: 'bumps naked minor',
    currentValue: '5.0',
    rangeStrategy: 'bump',
    fromVersion: '5.0.0',
    toVersion: '5.0.7',
    expectedValue: '5.0',
  },
  {
    title: 'bumps naked minor',
    currentValue: '5.0',
    rangeStrategy: 'bump',
    fromVersion: '5.0.0',
    toVersion: '5.1.7',
    expectedValue: '5.1',
  },
  {
    title: 'bumps naked minor',
    currentValue: '5.0',
    rangeStrategy: 'bump',
    fromVersion: '5.0.0',
    toVersion: '6.1.7',
    expectedValue: '6.1',
  },
  {
    title: 'replaces minor',
    currentValue: '5.0',
    rangeStrategy: 'replace',
    fromVersion: '5.0.0',
    toVersion: '6.1.7',
    expectedValue: '6.1',
  },
  {
    title: 'replaces equals',
    currentValue: '=1.0.0',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '=1.1.0',
  },
  {
    title: 'bumps caret to prerelease',
    currentValue: '^1',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.0.7-prerelease.1',
    expectedValue: '^1.0.7-prerelease.1',
  },
  {
    title: 'replaces with newer',
    currentValue: '^1.0.0',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '1.0.7',
    expectedValue: '^1.0.7',
  },
  {
    title: 'bumps short tilde',
    currentValue: '~1.0',
    rangeStrategy: 'bump',
    fromVersion: '1.0.0',
    toVersion: '1.1.7',
    expectedValue: '~1.1',
  },
  {
    title: 'handles long asterisk',
    currentValue: '1.0.*',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '1.1.0',
    expectedValue: '1.1.*',
  },
  {
    title: 'handles short asterisk',
    currentValue: '1.*',
    rangeStrategy: 'replace',
    fromVersion: '1.0.0',
    toVersion: '2.1.0',
    expectedValue: '2.*',
  },
  {
    title: 'handles updating from stable to unstable',
    currentValue: '~0.6.1',
    rangeStrategy: 'replace',
    fromVersion: '0.6.8',
    toVersion: '0.7.0-rc.2',
    expectedValue: '~0.7.0-rc',
  },
  {
    title: 'handles less than version requirements',
    currentValue: '<1.3.4',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '1.5.0',
    expectedValue: '<1.5.1',
  },
  {
    title: 'handles less than version requirements',
    currentValue: '< 1.3.4',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '1.5.0',
    expectedValue: '< 1.5.1',
  },
  {
    title: 'handles less than version requirements',
    currentValue: '<   1.3.4',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '1.5.0',
    expectedValue: '< 1.5.1',
  },
  {
    title: 'handles less than equals version requirements',
    currentValue: '<=1.3.4',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '1.5.0',
    expectedValue: '<=1.5.0',
  },
  {
    title: 'handles less than equals version requirements',
    currentValue: '<= 1.3.4',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '1.5.0',
    expectedValue: '<= 1.5.0',
  },
  {
    title: 'handles less than equals version requirements',
    currentValue: '<=   1.3.4',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '1.5.0',
    expectedValue: '<= 1.5.0',
  },
  {
    title: 'handles replacing short caret versions',
    currentValue: '^1.2',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '2.0.0',
    expectedValue: '^2.0',
  },
  {
    title: 'handles replacing short caret versions',
    currentValue: '^1',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '2.0.0',
    expectedValue: '^2',
  },
  {
    title: 'handles replacing short tilde versions',
    currentValue: '~1.2',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '2.0.0',
    expectedValue: '~2.0',
  },
  {
    title: 'handles replacing short tilde versions',
    currentValue: '~1',
    rangeStrategy: 'replace',
    fromVersion: '1.2.3',
    toVersion: '2.0.0',
    expectedValue: '~2',
  },
];

const minMaxSample: MinMaxSatisfyingSampleElem[] = [
  {
    versionList: ['0.4.0', '0.5.0', '4.2.0', '4.3.0', '5.0.0'],
    range: '4.*, > 4.2',
    min: '4.3.0',
    max: '4.3.0',
  },
  {
    versionList: ['0.4.0', '0.5.0', '4.2.0', '5.0.0'],
    range: '^4.0.0',
    min: '4.2.0',
    max: '4.2.0',
  },
  {
    versionList: ['0.4.0', '0.5.0', '4.2.0', '5.0.0'],
    range: '^4.0.0, = 0.5.0',
    min: null,
    max: null,
  },
  {
    versionList: ['0.4.0', '0.5.0', '4.2.0', '5.0.0'],
    range: '^4.0.0, > 4.1.0, <= 4.3.5',
    min: '4.2.0',
    max: '4.2.0',
  },
  {
    versionList: ['0.4.0', '0.5.0', '4.2.0', '5.0.0'],
    range: '^6.2.0, 3.*',
    min: null,
    max: null,
  },
  {
    versionList: ['4.2.1', '0.4.0', '0.5.0', '4.0.0', '4.2.0', '5.0.0'],
    range: '4.*.0, < 4.2.5',
    min: '4.0.0',
    max: '4.2.1',
  },
  {
    versionList: ['0.4.0', '0.5.0', '4.0.0', '4.2.0', '5.0.0', '5.0.3'],
    range: '5.0, > 5.0.0',
    min: '5.0.3',
    max: '5.0.3',
  },
];

export const sample = {
  singleVersions: [...npmSample.singleVersions, ...pep440Sample.singleVersions],
  exactVersions: [...npmSample.exactVersions, ...pep440Sample.singleVersions],
  invalidInputs: [
    '1.2.3foo',
    'renovatebot/renovate',
    'renovatebot/renovate#master',
    'https://github.com/renovatebot/renovate.git',
  ],
  ranges: [...npmSample.ranges, ...pep440Sample.ranges],
  minMaxSample: [...pep440Sample.minMaxSample, ...minMaxSample],
  getNewValueTestCases: [
    ...getNewValueTestCases,
    ...npmSample.getNewValueTestCases,
    ...pep440Sample.getNewValueTestCases,
  ],
};
