import { Fixtures } from '~test/fixtures.ts';
import { logger } from '~test/util.ts';
import { smartTruncate } from './pr-body.ts';

const prBody = Fixtures.get('pr-body.txt');

describe('modules/platform/utils/pr-body', () => {
  describe('.smartTruncate', () => {
    it('truncates to 1000', () => {
      const body = smartTruncate(prBody, 1000);
      expect(body).toMatchInlineSnapshot(`
        "> ℹ️ **Note**
        > 
        > This PR body was truncated due to platform limits.

        This PR contains the following updates:

        | Package | Type | Update | Change |
        |---|---|---|---|
        | [renovate/renovate](https://togithub.com/renovatebot/renovate) | final | minor | \`19.46.0-slim\` -> \`19.47.0-slim\` |

        ---

        ### Release Notes

        <details>
        <summa

        > ✂ **Note**
        > 
        > PR body was truncated to here.


        </details>

        ---

        ### Configuration

        :date: **Schedule**: At any time (no schedule defined).

        :vertical_traffic_light: **Automerge**: Enabled.

        :recycle: **Rebasing**: Whenever PR becomes conflicted, or if you modify the PR title to begin with "\`rebase!\`".

        :no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

        ---

         - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox

        ---

        This PR has been generated by [Mend Renovate](https://togithub.com/marketplace/renovate). View repository job log [here](https://renovatebot.com/dashboard#VisualOn/docker-images).
        "
      `);
      expect(body.length < prBody.length).toBe(true);
      expect(logger.logger.debug).toHaveBeenCalledWith(
        'Truncating PR body due to platform limitation of 1000 characters',
      );
    });

    it('truncates to 300 not smart', () => {
      const body = smartTruncate(prBody, 300);
      expect(body).toMatchInlineSnapshot(`
        "> ℹ️ **Note**
        > 
        > This PR body was truncated due to platform limits.

        This PR contains the following updates:

        | Package | Type | Update | Change |
        |---|---|---|---|
        | [renovate/renovate](https://togithub.com/renovatebot/renovate) | final | minor |

        > ✂ **Note**
        > 
        > PR body was truncated to here.
        "
      `);
      expect(body).toHaveLength(300);
      expect(logger.logger.debug).toHaveBeenCalledWith(
        'Truncating PR body due to platform limitation of 300 characters',
      );
    });

    it('includes truncation notice at end of truncated content (when "not smart")', () => {
      const body = smartTruncate(prBody, 300);
      expect(body).toContain('PR body was truncated to here');
      expect(body).toHaveLength(300);
    });

    it('includes truncation notice before Configuration section (when "smart")', () => {
      const body = smartTruncate(prBody, 3000);
      expect(body.length).toBeLessThanOrEqual(3000);
      expect(body).toContain('PR body was truncated to here');
      expect(body).toContain('### Configuration');
      expect(body.indexOf('PR body was truncated to here')).toBeLessThan(
        body.indexOf('### Configuration'),
      );
    });

    it('truncates content without release notes structure when notice fits', () => {
      const body = smartTruncate('x'.repeat(500), 200);
      expect(body).toHaveLength(200);
      expect(body).toContain('PR body was truncated to here');
    });

    it('truncates to below notice length with release notes structure', () => {
      const body = smartTruncate(prBody, 50);
      expect(body).toHaveLength(50);
      expect(body).not.toContain('PR body was truncated to here');
    });

    it('truncates to 10', () => {
      const body = smartTruncate('Lorem ipsum dolor sit amet', 10);
      expect(body).toBe('> ℹ️ **Not');
      expect(logger.logger.debug).toHaveBeenCalledWith(
        'Truncating PR body due to platform limitation of 10 characters',
      );
    });

    it('does not truncate', () => {
      expect(smartTruncate(prBody, 60000)).toEqual(prBody);
    });
  });
});
