import { Fixtures } from '~test/fixtures.ts';
import * as httpMock from '~test/http-mock.ts';
import { partial } from '~test/util.ts';
import { ExternalHostError } from '../../../types/errors/external-host-error.ts';
import { id as versioning } from '../../versioning/gradle/index.ts';
import type { GetPkgReleasesConfig, GetReleasesConfig } from '../index.ts';
import { getPkgReleases } from '../index.ts';
import { GradleVersionDatasource } from './index.ts';

const allResponse = Fixtures.get('all.json');

let config: GetPkgReleasesConfig;

const datasource = GradleVersionDatasource.id;

describe('modules/datasource/gradle-version/index', () => {
  describe('getReleases', () => {
    beforeEach(() => {
      config = {
        datasource,
        versioning,
        packageName: 'abc',
      };
    });

    it('processes real data', async () => {
      httpMock
        .scope('https://services.gradle.org/')
        .get('/versions/all')
        .reply(200, allResponse);
      const res = await getPkgReleases(config);
      expect(res).toMatchObject({
        homepage: 'https://gradle.org',
        sourceUrl: 'https://github.com/gradle/gradle',
        releases: [
          {
            version: '0.7',
            gitRef: 'v0.7.0',
            releaseTimestamp: '2009-07-20T06:50:13.000Z',
          },
          { version: '0.8' },
          {
            version: '0.9-rc-1',
            gitRef: 'v0.9.0-RC1',
            releaseTimestamp: '2010-08-03T21:04:33.000Z',
          },
          { version: '0.9-rc-2' },
          { version: '0.9-rc-3' },
          { version: '0.9' },
          {
            version: '0.9.1',
            gitRef: 'v0.9.1',
            releaseTimestamp: '2011-01-02T00:40:57.000Z',
          },
          { version: '0.9.2' },
          { version: '1.0-milestone-1' },
          { version: '1.0-milestone-2' },
          { version: '1.0-milestone-3' },
          {
            version: '1.0-milestone-4',
            gitRef: 'v1.0.0-M4',
            releaseTimestamp: '2011-07-28T08:38:22.000Z',
            isDeprecated: true,
          },
          { version: '1.0-milestone-5' },
          { version: '1.0-milestone-6' },
          { version: '1.0-milestone-7' },
          {
            version: '1.0-milestone-8a',
            gitRef: 'v1.0.0-M8a',
            releaseTimestamp: '2012-02-20T17:53:57.000Z',
          },
          { version: '1.0-milestone-8' },
          { version: '1.0-milestone-9' },
          { version: '1.0-rc-1' },
          { version: '1.0-rc-2' },
          { version: '1.0-rc-3' },
          { version: '1.0' },
          { version: '1.1-rc-1' },
          { version: '1.1-rc-2' },
          { version: '1.1' },
          { version: '1.2-rc-1' },
          { version: '1.2' },
          { version: '1.3-rc-1' },
          { version: '1.3-rc-2' },
          { version: '1.3' },
          { version: '1.4-rc-1' },
          { version: '1.4-rc-2' },
          { version: '1.4-rc-3' },
          { version: '1.4' },
          { version: '1.5-rc-1' },
          { version: '1.5-rc-2' },
          { version: '1.5-rc-3' },
          { version: '1.5' },
          { version: '1.6-rc-1' },
          { version: '1.6' },
          { version: '1.7-rc-1' },
          { version: '1.7-rc-2' },
          { version: '1.7' },
          { version: '1.8-rc-1' },
          { version: '1.8-rc-2' },
          { version: '1.8' },
          { version: '1.9-rc-1' },
          { version: '1.9-rc-2' },
          { version: '1.9-rc-3' },
          { version: '1.9-rc-4' },
          { version: '1.9' },
          { version: '1.10-rc-1' },
          { version: '1.10-rc-2' },
          { version: '1.10' },
          { version: '1.11-rc-1' },
          { version: '1.11' },
          { version: '1.12-rc-1' },
          { version: '1.12-rc-2' },
          { version: '1.12' },
          { version: '2.0-rc-1' },
          { version: '2.0-rc-2' },
          { version: '2.0' },
          { version: '2.1-rc-1' },
          { version: '2.1-rc-2' },
          { version: '2.1-rc-3' },
          { version: '2.1-rc-4' },
          { version: '2.1' },
          { version: '2.2-rc-1' },
          { version: '2.2-rc-2' },
          { version: '2.2' },
          { version: '2.2.1-rc-1' },
          { version: '2.2.1' },
          { version: '2.3-rc-1' },
          { version: '2.3-rc-2' },
          { version: '2.3-rc-3' },
          { version: '2.3-rc-4' },
          { version: '2.3' },
          { version: '2.4-rc-1' },
          { version: '2.4-rc-2' },
          { version: '2.4' },
          { version: '2.5-rc-1' },
          { version: '2.5-rc-2' },
          { version: '2.5' },
          { version: '2.6-rc-1' },
          { version: '2.6-rc-2' },
          { version: '2.6' },
          { version: '2.7-rc-1' },
          { version: '2.7-rc-2' },
          { version: '2.7' },
          { version: '2.8-rc-1' },
          { version: '2.8-rc-2' },
          { version: '2.8' },
          { version: '2.9-rc-1' },
          { version: '2.9' },
          { version: '2.10-rc-1' },
          { version: '2.10-rc-2' },
          { version: '2.10' },
          { version: '2.11-rc-1' },
          { version: '2.11-rc-2' },
          { version: '2.11-rc-3' },
          { version: '2.11' },
          { version: '2.12-rc-1' },
          { version: '2.12' },
          { version: '2.13-rc-1' },
          { version: '2.13-rc-2' },
          { version: '2.13' },
          { version: '2.14-rc-1' },
          { version: '2.14-rc-2' },
          { version: '2.14-rc-3' },
          { version: '2.14-rc-4' },
          { version: '2.14-rc-5' },
          { version: '2.14-rc-6' },
          { version: '2.14' },
          { version: '2.14.1-rc-1' },
          { version: '2.14.1-rc-2' },
          { version: '2.14.1' },
          { version: '3.0-milestone-1' },
          { version: '3.0-milestone-2' },
          { version: '3.0-rc-1' },
          { version: '3.0-rc-2' },
          { version: '3.0' },
          { version: '3.1-rc-1' },
          { version: '3.1' },
          { version: '3.2-rc-1' },
          { version: '3.2-rc-2' },
          { version: '3.2-rc-3' },
          { version: '3.2' },
          { version: '3.2.1' },
          { version: '3.3-rc-1' },
          { version: '3.3' },
          { version: '3.4-rc-1' },
          { version: '3.4-rc-2' },
          { version: '3.4-rc-3' },
          { version: '3.4' },
          { version: '3.4.1' },
          { version: '3.5-rc-1' },
          { version: '3.5-rc-2' },
          { version: '3.5-rc-3' },
          { version: '3.5' },
          { version: '3.5.1' },
          { version: '4.0-milestone-1' },
          { version: '4.0-milestone-2' },
          { version: '4.0-rc-1' },
          { version: '4.0-rc-2' },
          { version: '4.0-rc-3' },
          { version: '4.0' },
          { version: '4.0.1' },
          { version: '4.0.2' },
          { version: '4.1-milestone-1' },
          { version: '4.1-rc-1' },
          { version: '4.1-rc-2' },
          { version: '4.1' },
          { version: '4.2-rc-1' },
          { version: '4.2-rc-2' },
          { version: '4.2' },
          { version: '4.2.1' },
          { version: '4.3-rc-1' },
          { version: '4.3-rc-2' },
          { version: '4.3-rc-3' },
          { version: '4.3-rc-4' },
          { version: '4.3' },
          { version: '4.3.1' },
          { version: '4.4-rc-1' },
          { version: '4.4-rc-2' },
          { version: '4.4-rc-3' },
          { version: '4.4-rc-4' },
          { version: '4.4-rc-5' },
          { version: '4.4-rc-6' },
          { version: '4.4' },
          { version: '4.4.1' },
          { version: '4.5-rc-1' },
          { version: '4.5-rc-2' },
          { version: '4.5' },
          { version: '4.5.1' },
          { version: '4.6-rc-1' },
          { version: '4.6-rc-2' },
          { version: '4.6' },
          { version: '4.7-rc-1' },
          { version: '4.7-rc-2' },
          { version: '4.7' },
          { version: '4.8-rc-1' },
          { version: '4.8-rc-2' },
          { version: '4.8-rc-3' },
          { version: '4.8' },
          { version: '4.8.1' },
          { version: '4.9-rc-1' },
          { version: '4.9-rc-2' },
          { version: '4.9' },
          { version: '4.10-rc-1' },
          { version: '4.10-rc-2' },
          { version: '4.10-rc-3' },
          { version: '4.10' },
          { version: '4.10.1' },
          { version: '4.10.2' },
          { version: '4.10.3' },
          { version: '5.0-milestone-1' },
          { version: '5.0-rc-1' },
          { version: '5.0-rc-2' },
          { version: '5.0-rc-3' },
          { version: '5.0-rc-4' },
          { version: '5.0-rc-5' },
          { version: '5.0' },
          { version: '5.1-milestone-1' },
          { version: '5.1-rc-1' },
          { version: '5.1-rc-2' },
          { version: '5.1-rc-3' },
          { version: '5.1' },
          { version: '5.1.1' },
          { version: '5.2-rc-1' },
          { version: '5.2' },
          { version: '5.2.1' },
          { version: '5.3-rc-1' },
          { version: '5.3-rc-2' },
          { version: '5.3-rc-3' },
          { version: '5.3' },
          { version: '5.3.1' },
          { version: '5.4-rc-1' },
          { version: '5.4' },
          { version: '5.4.1' },
          { version: '5.5-rc-1' },
          { version: '5.5-rc-2' },
          { version: '5.5-rc-3' },
          { version: '5.5-rc-4' },
          { version: '5.5' },
          { version: '5.5.1' },
          { version: '5.6-rc-1' },
          { version: '5.6-rc-2' },
          { version: '5.6' },
          { version: '5.6.1' },
          { version: '5.6.2' },
          { version: '5.6.3' },
          { version: '5.6.4' },
          { version: '6.0-rc-1' },
          { version: '6.0-rc-2' },
          { version: '6.0-rc-3' },
          { version: '6.0' },
          { version: '6.0.1' },
          { version: '6.1-milestone-1' },
          { version: '6.1-milestone-2' },
          { version: '6.1-milestone-3' },
          { version: '6.1-rc-1' },
          { version: '6.1-rc-2' },
          { version: '6.1-rc-3' },
          { version: '6.1' },
          { version: '6.1.1' },
          { version: '6.2-rc-1' },
          { version: '6.2-rc-2' },
          { version: '6.2-rc-3' },
          { version: '6.2' },
          { version: '6.2.1' },
          { version: '6.2.2' },
          { version: '6.3-rc-1' },
          { version: '6.3-rc-2' },
          { version: '6.3-rc-3' },
          { version: '6.3-rc-4' },
          { version: '6.3' },
          { version: '6.4-rc-1' },
          { version: '6.4-rc-2' },
          { version: '6.4-rc-3' },
          { version: '6.4-rc-4' },
          { version: '6.4' },
          { version: '6.4.1' },
          { version: '6.5-milestone-1' },
          { version: '6.5-milestone-2' },
          { version: '6.5-rc-1' },
          { version: '6.5' },
          { version: '6.5.1' },
          { version: '6.6-milestone-1' },
          { version: '6.6-milestone-2' },
          { version: '6.6-milestone-3' },
          { version: '6.6-rc-1' },
          { version: '6.6-rc-2' },
          { version: '6.6-rc-3' },
          { version: '6.6-rc-4' },
          { version: '6.6-rc-5' },
          { version: '6.6-rc-6' },
          { version: '6.6' },
          { version: '6.6.1' },
          { version: '6.7-rc-1' },
          { version: '6.7-rc-2' },
          { version: '6.7-rc-3' },
          { version: '6.7-rc-4' },
          { version: '6.7-rc-5' },
          { version: '6.7' },
          { version: '6.7.1' },
          { version: '6.8-milestone-1' },
          { version: '6.8-milestone-2' },
          { version: '6.8-milestone-3' },
          { version: '6.8-rc-1' },
          { version: '6.8-rc-3' },
          { version: '6.8-rc-4' },
          { version: '6.8-rc-5' },
          { version: '6.8' },
          { version: '6.8.1' },
          { version: '6.8.2' },
          { version: '6.8.3' },
          { version: '7.0-milestone-1' },
          { version: '7.0-milestone-2' },
          { version: '7.0-milestone-3' },
          {
            version: '7.0-rc-1',
            gitRef: 'v7.0.0-RC1',
            releaseTimestamp: '2021-03-23T01:02:30.000Z',
          },
        ],
      });
      expect(res).not.toBeNull();
      expect(res?.releases).toHaveLength(300);
      expect(
        res?.releases.filter(({ isDeprecated }) => isDeprecated),
      ).toHaveLength(1);
    });

    it('calls configured registryUrls', async () => {
      httpMock.scope('https://foo.bar').get('/').reply(200, allResponse);

      httpMock
        .scope('http://baz.qux')
        .get('/')
        .reply(200, [
          { version: '1.0.1' },
          { version: '1.0.2', buildTime: 'abc' },
        ]);

      const res = await getPkgReleases({
        ...config,
        registryUrls: ['https://foo.bar', 'http://baz.qux'],
      });
      expect(res).toMatchObject({
        homepage: 'https://gradle.org',
        sourceUrl: 'https://github.com/gradle/gradle',
        releases: [
          { version: '0.7', registryUrl: 'https://foo.bar' },
          { version: '0.8' },
          { version: '0.9-rc-1' },
          { version: '0.9-rc-2' },
          { version: '0.9-rc-3' },
          { version: '0.9' },
          { version: '0.9.1' },
          { version: '0.9.2' },
          { version: '1.0-milestone-1' },
          { version: '1.0-milestone-2' },
          { version: '1.0-milestone-3' },
          { version: '1.0-milestone-4' },
          { version: '1.0-milestone-5' },
          { version: '1.0-milestone-6' },
          { version: '1.0-milestone-7' },
          { version: '1.0-milestone-8a' },
          { version: '1.0-milestone-8' },
          { version: '1.0-milestone-9' },
          { version: '1.0-rc-1' },
          { version: '1.0-rc-2' },
          { version: '1.0-rc-3' },
          { version: '1.0' },
          { version: '1.0.1', registryUrl: 'http://baz.qux' },
          { version: '1.0.2', registryUrl: 'http://baz.qux' },
          { version: '1.1-rc-1' },
          { version: '1.1-rc-2' },
          { version: '1.1' },
          { version: '1.2-rc-1' },
          { version: '1.2' },
          { version: '1.3-rc-1' },
          { version: '1.3-rc-2' },
          { version: '1.3' },
          { version: '1.4-rc-1' },
          { version: '1.4-rc-2' },
          { version: '1.4-rc-3' },
          { version: '1.4' },
          { version: '1.5-rc-1' },
          { version: '1.5-rc-2' },
          { version: '1.5-rc-3' },
          { version: '1.5' },
          { version: '1.6-rc-1' },
          { version: '1.6' },
          { version: '1.7-rc-1' },
          { version: '1.7-rc-2' },
          { version: '1.7' },
          { version: '1.8-rc-1' },
          { version: '1.8-rc-2' },
          { version: '1.8' },
          { version: '1.9-rc-1' },
          { version: '1.9-rc-2' },
          { version: '1.9-rc-3' },
          { version: '1.9-rc-4' },
          { version: '1.9' },
          { version: '1.10-rc-1' },
          { version: '1.10-rc-2' },
          { version: '1.10' },
          { version: '1.11-rc-1' },
          { version: '1.11' },
          { version: '1.12-rc-1' },
          { version: '1.12-rc-2' },
          { version: '1.12' },
          { version: '2.0-rc-1' },
          { version: '2.0-rc-2' },
          { version: '2.0' },
          { version: '2.1-rc-1' },
          { version: '2.1-rc-2' },
          { version: '2.1-rc-3' },
          { version: '2.1-rc-4' },
          { version: '2.1' },
          { version: '2.2-rc-1' },
          { version: '2.2-rc-2' },
          { version: '2.2' },
          { version: '2.2.1-rc-1' },
          { version: '2.2.1' },
          { version: '2.3-rc-1' },
          { version: '2.3-rc-2' },
          { version: '2.3-rc-3' },
          { version: '2.3-rc-4' },
          { version: '2.3' },
          { version: '2.4-rc-1' },
          { version: '2.4-rc-2' },
          { version: '2.4' },
          { version: '2.5-rc-1' },
          { version: '2.5-rc-2' },
          { version: '2.5' },
          { version: '2.6-rc-1' },
          { version: '2.6-rc-2' },
          { version: '2.6' },
          { version: '2.7-rc-1' },
          { version: '2.7-rc-2' },
          { version: '2.7' },
          { version: '2.8-rc-1' },
          { version: '2.8-rc-2' },
          { version: '2.8' },
          { version: '2.9-rc-1' },
          { version: '2.9' },
          { version: '2.10-rc-1' },
          { version: '2.10-rc-2' },
          { version: '2.10' },
          { version: '2.11-rc-1' },
          { version: '2.11-rc-2' },
          { version: '2.11-rc-3' },
          { version: '2.11' },
          { version: '2.12-rc-1' },
          { version: '2.12' },
          { version: '2.13-rc-1' },
          { version: '2.13-rc-2' },
          { version: '2.13' },
          { version: '2.14-rc-1' },
          { version: '2.14-rc-2' },
          { version: '2.14-rc-3' },
          { version: '2.14-rc-4' },
          { version: '2.14-rc-5' },
          { version: '2.14-rc-6' },
          { version: '2.14' },
          { version: '2.14.1-rc-1' },
          { version: '2.14.1-rc-2' },
          { version: '2.14.1' },
          { version: '3.0-milestone-1' },
          { version: '3.0-milestone-2' },
          { version: '3.0-rc-1' },
          { version: '3.0-rc-2' },
          { version: '3.0' },
          { version: '3.1-rc-1' },
          { version: '3.1' },
          { version: '3.2-rc-1' },
          { version: '3.2-rc-2' },
          { version: '3.2-rc-3' },
          { version: '3.2' },
          { version: '3.2.1' },
          { version: '3.3-rc-1' },
          { version: '3.3' },
          { version: '3.4-rc-1' },
          { version: '3.4-rc-2' },
          { version: '3.4-rc-3' },
          { version: '3.4' },
          { version: '3.4.1' },
          { version: '3.5-rc-1' },
          { version: '3.5-rc-2' },
          { version: '3.5-rc-3' },
          { version: '3.5' },
          { version: '3.5.1' },
          { version: '4.0-milestone-1' },
          { version: '4.0-milestone-2' },
          { version: '4.0-rc-1' },
          { version: '4.0-rc-2' },
          { version: '4.0-rc-3' },
          { version: '4.0' },
          { version: '4.0.1' },
          { version: '4.0.2' },
          { version: '4.1-milestone-1' },
          { version: '4.1-rc-1' },
          { version: '4.1-rc-2' },
          { version: '4.1' },
          { version: '4.2-rc-1' },
          { version: '4.2-rc-2' },
          { version: '4.2' },
          { version: '4.2.1' },
          { version: '4.3-rc-1' },
          { version: '4.3-rc-2' },
          { version: '4.3-rc-3' },
          { version: '4.3-rc-4' },
          { version: '4.3' },
          { version: '4.3.1' },
          { version: '4.4-rc-1' },
          { version: '4.4-rc-2' },
          { version: '4.4-rc-3' },
          { version: '4.4-rc-4' },
          { version: '4.4-rc-5' },
          { version: '4.4-rc-6' },
          { version: '4.4' },
          { version: '4.4.1' },
          { version: '4.5-rc-1' },
          { version: '4.5-rc-2' },
          { version: '4.5' },
          { version: '4.5.1' },
          { version: '4.6-rc-1' },
          { version: '4.6-rc-2' },
          { version: '4.6' },
          { version: '4.7-rc-1' },
          { version: '4.7-rc-2' },
          { version: '4.7' },
          { version: '4.8-rc-1' },
          { version: '4.8-rc-2' },
          { version: '4.8-rc-3' },
          { version: '4.8' },
          { version: '4.8.1' },
          { version: '4.9-rc-1' },
          { version: '4.9-rc-2' },
          { version: '4.9' },
          { version: '4.10-rc-1' },
          { version: '4.10-rc-2' },
          { version: '4.10-rc-3' },
          { version: '4.10' },
          { version: '4.10.1' },
          { version: '4.10.2' },
          { version: '4.10.3' },
          { version: '5.0-milestone-1' },
          { version: '5.0-rc-1' },
          { version: '5.0-rc-2' },
          { version: '5.0-rc-3' },
          { version: '5.0-rc-4' },
          { version: '5.0-rc-5' },
          { version: '5.0' },
          { version: '5.1-milestone-1' },
          { version: '5.1-rc-1' },
          { version: '5.1-rc-2' },
          { version: '5.1-rc-3' },
          { version: '5.1' },
          { version: '5.1.1' },
          { version: '5.2-rc-1' },
          { version: '5.2' },
          { version: '5.2.1' },
          { version: '5.3-rc-1' },
          { version: '5.3-rc-2' },
          { version: '5.3-rc-3' },
          { version: '5.3' },
          { version: '5.3.1' },
          { version: '5.4-rc-1' },
          { version: '5.4' },
          { version: '5.4.1' },
          { version: '5.5-rc-1' },
          { version: '5.5-rc-2' },
          { version: '5.5-rc-3' },
          { version: '5.5-rc-4' },
          { version: '5.5' },
          { version: '5.5.1' },
          { version: '5.6-rc-1' },
          { version: '5.6-rc-2' },
          { version: '5.6' },
          { version: '5.6.1' },
          { version: '5.6.2' },
          { version: '5.6.3' },
          { version: '5.6.4' },
          { version: '6.0-rc-1' },
          { version: '6.0-rc-2' },
          { version: '6.0-rc-3' },
          { version: '6.0' },
          { version: '6.0.1' },
          { version: '6.1-milestone-1' },
          { version: '6.1-milestone-2' },
          { version: '6.1-milestone-3' },
          { version: '6.1-rc-1' },
          { version: '6.1-rc-2' },
          { version: '6.1-rc-3' },
          { version: '6.1' },
          { version: '6.1.1' },
          { version: '6.2-rc-1' },
          { version: '6.2-rc-2' },
          { version: '6.2-rc-3' },
          { version: '6.2' },
          { version: '6.2.1' },
          { version: '6.2.2' },
          { version: '6.3-rc-1' },
          { version: '6.3-rc-2' },
          { version: '6.3-rc-3' },
          { version: '6.3-rc-4' },
          { version: '6.3' },
          { version: '6.4-rc-1' },
          { version: '6.4-rc-2' },
          { version: '6.4-rc-3' },
          { version: '6.4-rc-4' },
          { version: '6.4' },
          { version: '6.4.1' },
          { version: '6.5-milestone-1' },
          { version: '6.5-milestone-2' },
          { version: '6.5-rc-1' },
          { version: '6.5' },
          { version: '6.5.1' },
          { version: '6.6-milestone-1' },
          { version: '6.6-milestone-2' },
          { version: '6.6-milestone-3' },
          { version: '6.6-rc-1' },
          { version: '6.6-rc-2' },
          { version: '6.6-rc-3' },
          { version: '6.6-rc-4' },
          { version: '6.6-rc-5' },
          { version: '6.6-rc-6' },
          { version: '6.6' },
          { version: '6.6.1' },
          { version: '6.7-rc-1' },
          { version: '6.7-rc-2' },
          { version: '6.7-rc-3' },
          { version: '6.7-rc-4' },
          { version: '6.7-rc-5' },
          { version: '6.7' },
          { version: '6.7.1' },
          { version: '6.8-milestone-1' },
          { version: '6.8-milestone-2' },
          { version: '6.8-milestone-3' },
          { version: '6.8-rc-1' },
          { version: '6.8-rc-3' },
          { version: '6.8-rc-4' },
          { version: '6.8-rc-5' },
          { version: '6.8' },
          { version: '6.8.1' },
          { version: '6.8.2' },
          { version: '6.8.3' },
          { version: '7.0-milestone-1' },
          { version: '7.0-milestone-2' },
          { version: '7.0-milestone-3' },
          { version: '7.0-rc-1', registryUrl: 'https://foo.bar' },
        ],
      });
      expect(res).not.toBeNull();
    });

    it('handles empty releases', async () => {
      httpMock
        .scope('https://services.gradle.org/')
        .get('/versions/all')
        .reply(200, []);

      const res = await getPkgReleases(config);
      expect(res).toBeNull();
    });

    it('handles errors', async () => {
      expect.assertions(2);
      httpMock
        .scope('https://services.gradle.org/')
        .get('/versions/all')
        .reply(500);

      httpMock.scope('http://baz.qux').get('/').reply(429);

      const gradleVersionDatasource = new GradleVersionDatasource();

      await expect(
        gradleVersionDatasource.getReleases(
          partial<GetReleasesConfig>({
            registryUrl: 'https://services.gradle.org/versions/all',
          }),
        ),
      ).rejects.toThrow(ExternalHostError);

      await expect(
        gradleVersionDatasource.getReleases(
          partial<GetReleasesConfig>({
            registryUrl: 'http://baz.qux',
          }),
        ),
      ).rejects.toThrow(ExternalHostError);
    });
  });
});
