# This file is generated by Dist::Zilla::Plugin::CPANFile v6.024
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "File::Spec" => "0";
requires "File::Temp" => "0";
requires "Scalar::Util" => "1.13";
requires "Storable" => "0";
requires "perl" => "5.006002";
requires "utf8" => "0";
suggests "Module::Pluggable" => "0";

on 'configure' => sub {
  requires "ExtUtils::MakeMaker" => "0";
};

on 'develop' => sub {
  requires "IPC::Open3" => "0";
  requires "Term::Table" => "0.013";
  requires "Test::Pod" => "1.41";
  requires "Test::Spelling" => "0.12";
};
