import type { Preset } from '../types';
import {
  PresetTemplate,
  Replacement,
  addPresets,
} from './auto-generate-replacements';

/* eslint sort-keys: ["error", "asc", {"caseSensitive": false, "natural": true}] */
export const presets: Record<string, Preset> = {
  all: {
    description: 'All replacements.',
    extends: [
      'replacements:apollo-server-to-scoped',
      'replacements:babel-eslint-to-eslint-parser',
      'replacements:cucumber-to-scoped',
      'replacements:fastify-to-scoped',
      'replacements:hapi-to-scoped',
      'replacements:jade-to-pug',
      'replacements:joi-to-scoped',
      'replacements:joi-to-unscoped',
      'replacements:middie-to-scoped',
      'replacements:now-to-vercel',
      'replacements:parcel-css-to-lightningcss',
      'replacements:react-query-devtools-to-scoped',
      'replacements:react-query-to-scoped',
      'replacements:react-scripts-ts-to-react-scripts',
      'replacements:renovate-pep440-to-renovatebot-pep440',
      'replacements:rollup-node-resolve-to-scoped',
      'replacements:vso-task-lib-to-azure-pipelines-task-lib',
      'replacements:vsts-task-lib-to-azure-pipelines-task-lib',
      'replacements:xmldom-to-scoped',
    ],
  },
  'apollo-server-to-scoped': {
    description: '`apollo-server` packages became scoped',
    packageRules: [
      {
        matchCurrentVersion: '>=3.10.3',
        matchDatasources: ['npm'],
        matchPackageNames: [
          'apollo-server',
          'apollo-server-core',
          'apollo-server-express',
        ],
        replacementName: '@apollo/server',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=3.3.1',
        matchDatasources: ['npm'],
        matchPackageNames: ['apollo-server-errors'],
        replacementName: '@apollo/server',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=3.6.3',
        matchDatasources: ['npm'],
        matchPackageNames: ['apollo-server-types', 'apollo-server-plugin-base'],
        replacementName: '@apollo/server',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=3.7.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['apollo-datasource-rest'],
        replacementName: '@apollo/datasource-rest',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=3.7.1',
        matchDatasources: ['npm'],
        matchPackageNames: ['apollo-server-plugin-response-cache'],
        replacementName: '@apollo/server-plugin-response-cache',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=3.5.1',
        matchDatasources: ['npm'],
        matchPackageNames: ['apollo-server-plugin-operation-registry'],
        replacementName: '@apollo/server-plugin-operation-registry',
        replacementVersion: '3.5.6',
      },
      {
        matchCurrentVersion: '>=3.3.3',
        matchDatasources: ['npm'],
        matchPackageNames: ['apollo-reporting-protobuf'],
        replacementName: '@apollo/usage-reporting-protobuf',
        replacementVersion: '4.0.0',
      },
    ],
  },
  'babel-eslint-to-eslint-parser': {
    description: '`babel-eslint` was renamed under the `@babel` scope.',
    packageRules: [
      {
        matchCurrentVersion: '>=7.11.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['babel-eslint'],
        replacementName: '@babel/eslint-parser',
        replacementVersion: '7.11.0',
      },
    ],
  },
  'cucumber-to-scoped': {
    description: '`cucumber` became scoped.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['cucumber'],
        replacementName: '@cucumber/cucumber',
        replacementVersion: '7.0.0',
      },
    ],
  },
  'fastify-to-scoped': {
    description: '`fastify` packages became scoped',
    packageRules: [
      {
        matchCurrentVersion: '>=3.3.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-accepts-serializer'],
        replacementName: '@fastify/accepts-serializer',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=2.3.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-accepts'],
        replacementName: '@fastify/accepts',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=1.2.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-auth'],
        replacementName: '@fastify/auth',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=3.13.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-autoload'],
        replacementName: '@fastify/autoload',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=1.3.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-awilix'],
        replacementName: '@fastify/awilix',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=2.3.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-basic-auth'],
        replacementName: '@fastify/basic-auth',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=6.3.0 <7.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-bearer-auth'],
        replacementName: '@fastify/bearer-auth',
        replacementVersion: '7.0.0',
      },
      {
        matchCurrentVersion: '>=6.3.0 <7.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-caching'],
        replacementName: '@fastify/caching',
        replacementVersion: '7.0.0',
      },
      {
        matchCurrentVersion: '>=1.2.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-circuit-breaker'],
        replacementName: '@fastify/circuit-breaker',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=4.1.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-compress'],
        replacementName: '@fastify/compress',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=5.7.0 <6.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-cookie'],
        replacementName: '@fastify/cookie',
        replacementVersion: '6.0.0',
      },
      {
        matchCurrentVersion: '>=6.1.0 <7.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-cors'],
        replacementName: '@fastify/cors',
        replacementVersion: '7.0.0',
      },
      {
        matchCurrentVersion: '>=1.1.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-diagnostics-channel'],
        replacementName: '@fastify/diagnostics-channel',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=1.2.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-elasticsearch'],
        replacementName: '@fastify/elasticsearch',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=2.2.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-env'],
        replacementName: '@fastify/env',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=1.2.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-error'],
        replacementName: '@fastify/error',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=2.2.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-etag'],
        replacementName: '@fastify/etag',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=0.4.0 <1.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-express'],
        replacementName: '@fastify/express',
        replacementVersion: '1.0.0',
      },
      {
        matchCurrentVersion: '>=3.1.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-flash'],
        replacementName: '@fastify/flash',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=5.3.0 <6.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-formbody'],
        replacementName: '@fastify/formbody',
        replacementVersion: '6.0.0',
      },
      {
        matchCurrentVersion: '>=1.1.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-funky'],
        replacementName: '@fastify/funky',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=7.1.0 <8.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-helmet'],
        replacementName: '@fastify/helmet',
        replacementVersion: '8.0.0',
      },
      {
        matchCurrentVersion: '>=0.3.0 <1.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-hotwire'],
        replacementName: '@fastify/hotwire',
        replacementVersion: '1.0.0',
      },
      {
        matchCurrentVersion: '>=6.3.0 <7.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-http-proxy'],
        replacementName: '@fastify/http-proxy',
        replacementVersion: '7.0.0',
      },
      {
        matchCurrentVersion: '>=4.2.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-jwt'],
        replacementName: '@fastify/jwt',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=0.3.0 <1.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-kafka'],
        replacementName: '@fastify/kafka',
        replacementVersion: '1.0.0',
      },
      {
        matchCurrentVersion: '>=3.2.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-leveldb'],
        replacementName: '@fastify/leveldb',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=4.2.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-mongodb'],
        replacementName: '@fastify/mongodb',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=5.4.0 <6.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-multipart'],
        replacementName: '@fastify/multipart',
        replacementVersion: '6.0.0',
      },
      {
        matchCurrentVersion: '>=2.2.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-mysql'],
        replacementName: '@fastify/mysql',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=7.3.0 <8.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-nextjs'],
        replacementName: '@fastify/nextjs',
        replacementVersion: '8.0.0',
      },
      {
        matchCurrentVersion: '>=4.6.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-oauth2'],
        replacementName: '@fastify/oauth2',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=0.5.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-passport'],
        replacementName: '@fastify/passport',
        replacementVersion: '1.0.0',
      },
      {
        matchCurrentVersion: '>=3.7.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-postgres'],
        replacementName: '@fastify/postgres',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=5.9.0 <6.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-rate-limit'],
        replacementName: '@fastify/rate-limit',
        replacementVersion: '6.0.0',
      },
      {
        matchCurrentVersion: '>=4.4.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-redis'],
        replacementName: '@fastify/redis',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=6.7.0 <7.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-reply-from'],
        replacementName: '@fastify/reply-from',
        replacementVersion: '7.0.0',
      },
      {
        matchCurrentVersion: '>=2.3.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-request-context'],
        replacementName: '@fastify/request-context',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=0.3.0 <1.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-response-validation'],
        replacementName: '@fastify/response-validation',
        replacementVersion: '1.0.0',
      },
      {
        matchCurrentVersion: '>=2.1.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-routes-stats'],
        replacementName: '@fastify/routes-stats',
        replacementVersion: '3.0.0',
      },
      {
        matchCurrentVersion: '>=3.2.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-routes'],
        replacementName: '@fastify/routes',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=1.1.0 <2.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-schedule'],
        replacementName: '@fastify/schedule',
        replacementVersion: '2.0.0',
      },
      {
        matchCurrentVersion: '>=3.2.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-secure-session'],
        replacementName: '@fastify/secure-session',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=3.2.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-sensible'],
        replacementName: '@fastify/sensible',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=0.3.0 <1.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-soap-client'],
        replacementName: '@fastify/soap-client',
        replacementVersion: '1.0.0',
      },
      {
        matchCurrentVersion: '>=4.7.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-static'],
        replacementName: '@fastify/static',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=5.2.0 <6.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-swagger'],
        replacementName: '@fastify/swagger',
        replacementVersion: '6.0.0',
      },
      {
        matchCurrentVersion: '>=3.1.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-url-data'],
        replacementName: '@fastify/url-data',
        replacementVersion: '4.0.0',
      },
      {
        matchCurrentVersion: '>=4.3.0 <5.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-websocket'],
        replacementName: '@fastify/websocket',
        replacementVersion: '5.0.0',
      },
      {
        matchCurrentVersion: '>=2.1.0 <3.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['fastify-zipkin'],
        replacementName: '@fastify/zipkin',
        replacementVersion: '3.0.0',
      },
    ],
  },
  'hapi-to-scoped': {
    description: '`hapi` became scoped.',
    packageRules: [
      {
        matchCurrentVersion: '>=18.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['hapi'],
        replacementName: '@hapi/hapi',
        replacementVersion: '18.2.0',
      },
    ],
  },
  'jade-to-pug': {
    description: 'Jade was renamed to Pug.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['jade'],
        replacementName: 'pug',
        replacementVersion: '2.0.0',
      },
    ],
  },
  'joi-to-scoped': {
    description: '`joi` became scoped under the `hapi` organization.',
    packageRules: [
      {
        matchCurrentVersion: '>=14.0.0 <14.4.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['joi'],
        replacementName: '@hapi/joi',
        replacementVersion: '14.4.0',
      },
    ],
  },
  'joi-to-unscoped': {
    description: '`joi` was moved out of the `hapi` organization.',
    packageRules: [
      {
        matchCurrentVersion: '>=17.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['@hapi/joi'],
        replacementName: 'joi',
        replacementVersion: '17.1.1',
      },
    ],
  },
  'middie-to-scoped': {
    description: '`middie` became scoped.',
    packageRules: [
      {
        matchCurrentVersion: '>=7.1.0 <8.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['middie'],
        replacementName: '@fastify/middie',
        replacementVersion: '8.0.0',
      },
    ],
  },
  'now-to-vercel': {
    description: '`now` was renamed to `vercel`.',
    packageRules: [
      {
        matchCurrentVersion: '>=21.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['now'],
        replacementName: 'vercel',
        replacementVersion: '21.0.0',
      },
    ],
  },
  'parcel-css-to-lightningcss': {
    description: '`@parcel/css` was renamed `lightningcss`.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['@parcel/css'],
        replacementName: 'lightningcss',
        replacementVersion: '1.14.0',
      },
    ],
  },
  'react-query-devtools-to-scoped': {
    description:
      '`react-query/devtools` became scoped under the `tanstack` organization.',
    packageRules: [
      {
        matchCurrentVersion: '>=2.0.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['react-query/devtools'],
        replacementName: '@tanstack/react-query-devtools',
        replacementVersion: '4.0.0',
      },
    ],
  },
  'react-query-to-scoped': {
    description:
      '`react-query` became scoped under the `tanstack` organization.',
    packageRules: [
      {
        matchCurrentVersion: '>=3.0.0 <4.0.0',
        matchDatasources: ['npm'],
        matchPackageNames: ['react-query'],
        replacementName: '@tanstack/react-query',
        replacementVersion: '4.0.5',
      },
    ],
  },
  'react-scripts-ts-to-react-scripts': {
    description: '`react-scripts` supports typescripts since version 2.1.0.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['react-scripts-ts'],
        replacementName: 'react-scripts',
        replacementVersion: '2.1.8',
      },
    ],
  },
  'redux-devtools-extension-to-scope': {
    description:
      'The `redux-devtools-extension` package was renamed to `@redux-devtools/extension`.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['redux-devtools-extension'],
        replacementName: '@redux-devtools/extension',
        replacementVersion: '3.0.0',
      },
    ],
  },
  'renovate-pep440-to-renovatebot-pep440': {
    description:
      'The `@renovate/pep440` package was renamed to `@renovatebot/pep440`.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['@renovate/pep440'],
        replacementName: '@renovatebot/pep440',
        replacementVersion: '1.0.0',
      },
    ],
  },
  'rollup-node-resolve-to-scoped': {
    description: 'The node-resolve plugin for rollup became scoped.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['rollup-plugin-node-resolve'],
        replacementName: '@rollup/plugin-node-resolve',
        replacementVersion: '6.0.0',
      },
    ],
  },
  'spectre-cli-to-spectre-console-cli': {
    description:
      'The `Spectre.Cli` package was renamed to `Spectre.Console.Cli`.',
    packageRules: [
      {
        matchDatasources: ['nuget'],
        matchPackageNames: ['Spectre.Cli'],
        replacementName: 'Spectre.Console.Cli',
        replacementVersion: '0.45.0',
      },
    ],
  },
  'vso-task-lib-to-azure-pipelines-task-lib': {
    description:
      'The `vso-task-lib` package is now published as `azure-pipelines-task-lib`.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['vso-task-lib'],
        replacementName: 'azure-pipelines-task-lib',
        replacementVersion: '3.4.0',
      },
    ],
  },
  'vsts-task-lib-to-azure-pipelines-task-lib': {
    description:
      'The `vsts-task-lib` package is now published as `azure-pipelines-task-lib`.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['vsts-task-lib'],
        replacementName: 'azure-pipelines-task-lib',
        replacementVersion: '3.4.0',
      },
    ],
  },
  'xmldom-to-scoped': {
    description: 'The `xmldom` package is now published as `@xmldom/xmldom`.',
    packageRules: [
      {
        matchDatasources: ['npm'],
        matchPackageNames: ['xmldom', 'xmldom-alpha'],
        replacementName: '@xmldom/xmldom',
        replacementVersion: '0.7.5',
      },
    ],
  },
};

const muiReplacement: Replacement[] = [
  [['@material-ui/codemod'], '@mui/codemod'],
  [['@material-ui/core'], '@mui/material'],
  [['@material-ui/icons'], '@mui/icons-material'],
  [['@material-ui/lab'], '@mui/labs'],
  [['@material-ui/private-theming'], '@mui/private-theming'],
  [['@material-ui/styled-engine'], '@mui/styled-engine'],
  [['@material-ui/styled-engine-sc'], '@mui/styled-engine-sc'],
  [['@material-ui/styles'], '@mui/styles'],
  [['@material-ui/system'], '@mui/system'],
  [['@material-ui/types'], '@mui/types'],
  [['@material-ui/unstyled'], '@mui/core'],
];

const mui: PresetTemplate = {
  description:
    'The `material-ui` monorepo org was renamed from `@material-ui` to `@mui`.',
  packageRules: [
    {
      matchCurrentVersion: '>=4.0.0 <5.0.0',
      matchDatasources: ['npm'],
      replacements: muiReplacement,
      replacementVersion: '5.0.0',
    },
  ],
  title: 'material-ui-to-mui',
};

const k8sImages = [
  'addon-builder',
  'addon-manager/kube-addon-manager',
  'addon-manager/kube-addon-manager-amd64',
  'addon-manager/kube-addon-manager-arm',
  'addon-manager/kube-addon-manager-arm64',
  'addon-manager/kube-addon-manager-ppc64le',
  'addon-manager/kube-addon-manager-s390x',
  'addon-resizer',
  'addon-resizer-amd64',
  'addon-resizer-arm',
  'addon-resizer-arm64',
  'addon-resizer-ppc64le',
  'addon-resizer-s390x',
  'aggregator',
  'alpine-iptables-amd64',
  'alpine-iptables-arm',
  'alpine-iptables-arm64',
  'alpine-with-bash',
  'apisnoop/auditlogger',
  'apisnoop/snoopdb',
  'apparmor-loader',
  'artifact-promoter/cip',
  'artifact-promoter/cip-auditor',
  'artifact-promoter/kpromo',
  'artifact-promoter/kpromo-auditor',
  'artifact-promoter/vulndash',
  'autoscaling/addon-resizer',
  'autoscaling/addon-resizer-amd64',
  'autoscaling/addon-resizer-arm',
  'autoscaling/addon-resizer-arm64',
  'autoscaling/addon-resizer-ppc64le',
  'autoscaling/addon-resizer-s390x',
  'autoscaling/cluster-autoscaler',
  'autoscaling/cluster-autoscaler-amd64',
  'autoscaling/cluster-autoscaler-arm64',
  'autoscaling/vpa-admission-controller',
  'autoscaling/vpa-admission-controller-amd64',
  'autoscaling/vpa-admission-controller-arm',
  'autoscaling/vpa-admission-controller-arm64',
  'autoscaling/vpa-admission-controller-ppc64le',
  'autoscaling/vpa-admission-controller-s390x',
  'autoscaling/vpa-recommender',
  'autoscaling/vpa-recommender-amd64',
  'autoscaling/vpa-recommender-arm',
  'autoscaling/vpa-recommender-arm64',
  'autoscaling/vpa-recommender-ppc64le',
  'autoscaling/vpa-recommender-s390x',
  'autoscaling/vpa-updater',
  'autoscaling/vpa-updater-amd64',
  'autoscaling/vpa-updater-arm',
  'autoscaling/vpa-updater-arm64',
  'autoscaling/vpa-updater-ppc64le',
  'autoscaling/vpa-updater-s390x',
  'bom/bom',
  'build-image/debian-base',
  'build-image/debian-base-amd64',
  'build-image/debian-base-arm',
  'build-image/debian-base-arm64',
  'build-image/debian-base-ppc64le',
  'build-image/debian-base-s390x',
  'build-image/debian-hyperkube-base',
  'build-image/debian-hyperkube-base-amd64',
  'build-image/debian-hyperkube-base-arm',
  'build-image/debian-hyperkube-base-arm64',
  'build-image/debian-hyperkube-base-ppc64le',
  'build-image/debian-hyperkube-base-s390x',
  'build-image/debian-iptables',
  'build-image/debian-iptables-amd64',
  'build-image/debian-iptables-arm',
  'build-image/debian-iptables-arm64',
  'build-image/debian-iptables-ppc64le',
  'build-image/debian-iptables-s390x',
  'build-image/distroless-iptables',
  'build-image/distroless-iptables-amd64',
  'build-image/distroless-iptables-arm',
  'build-image/distroless-iptables-arm64',
  'build-image/distroless-iptables-ppc64le',
  'build-image/distroless-iptables-s390x',
  'build-image/go-runner',
  'build-image/go-runner-amd64',
  'build-image/go-runner-arm',
  'build-image/go-runner-arm64',
  'build-image/go-runner-ppc64le',
  'build-image/go-runner-s390x',
  'build-image/kube-cross',
  'build-image/kube-cross-amd64',
  'build-image/kube-cross-arm64',
  'build-image/kube-cross-ppc64le',
  'build-image/kube-cross-s390x',
  'build-image/setcap',
  'build-image/setcap-amd64',
  'build-image/setcap-arm',
  'build-image/setcap-arm64',
  'build-image/setcap-ppc64le',
  'build-image/setcap-s390x',
  'busybox',
  'cadvisor',
  'capi-cloudstack/capi-cloudstack-controller',
  'capi-docker/capd-manager',
  'capi-ibmcloud/cluster-api-ibmcloud-controller',
  'capi-kubeadm/cluster-api-kubeadm-controller',
  'capi-kubeadm/cluster-api-kubeadm-controller-amd64',
  'capi-kubeadm/cluster-api-kubeadm-controller-arm',
  'capi-kubeadm/cluster-api-kubeadm-controller-arm64',
  'capi-kubeadm/cluster-api-kubeadm-controller-ppc64le',
  'capi-kubeadm/cluster-api-kubeadm-controller-s390x',
  'capi-openstack/capi-openstack-controller',
  'capi-operator/cluster-api-operator',
  'cassandra',
  'cassandra-e2e-test',
  'check-metadata-concealment',
  'cloud-controller-manager',
  'cloud-controller-manager-amd64',
  'cloud-controller-manager-arm',
  'cloud-controller-manager-arm64',
  'cloud-controller-manager-ppc64le',
  'cloud-controller-manager-s390x',
  'cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver',
  'cloud-provider-gcp/gcp-filestore-csi-driver',
  'cloud-provider-ibm/ibm-powervs-block-csi-driver',
  'cloud-provider-ibm/ibm-vpc-block-csi-driver',
  'cloudsql-authenticator',
  'cluster-api-aws/cluster-api-aws-controller',
  'cluster-api-aws/cluster-api-aws-controller-amd64',
  'cluster-api-aws/cluster-api-aws-controller-arm',
  'cluster-api-aws/cluster-api-aws-controller-arm64',
  'cluster-api-aws/cluster-api-aws-controller-ppc64le',
  'cluster-api-aws/cluster-api-aws-controller-s390x',
  'cluster-api-aws/eks-bootstrap-controller',
  'cluster-api-aws/eks-controlplane-controller',
  'cluster-api-azure/cluster-api-azure-controller',
  'cluster-api-do/cluster-api-do-controller',
  'cluster-api-gcp/cluster-api-gcp-controller',
  'cluster-api-nested/cluster-api-nested-controller',
  'cluster-api-nested/nested-controlplane-controller',
  'cluster-api/cluster-api-controller',
  'cluster-api/cluster-api-controller-amd64',
  'cluster-api/cluster-api-controller-arm',
  'cluster-api/cluster-api-controller-arm64',
  'cluster-api/cluster-api-controller-ppc64le',
  'cluster-api/cluster-api-controller-s390x',
  'cluster-api/clusterctl',
  'cluster-api/kubeadm-bootstrap-controller',
  'cluster-api/kubeadm-control-plane-controller',
  'cluster-api/plantuml',
  'cluster-autoscaler',
  'cluster-proportional-autoscaler-amd64',
  'cluster-proportional-autoscaler-arm',
  'cluster-proportional-autoscaler-arm64',
  'cluster-proportional-autoscaler-ppc64le',
  'clusterapi-tester',
  'clusterregistry',
  'conformance',
  'conformance-amd64',
  'conformance-arm',
  'conformance-arm64',
  'conformance-ppc64le',
  'conformance-s390x',
  'coredns',
  'coredns/coredns',
  'cos-kernel-headers',
  'cos-nvidia-driver-install',
  'cpa/cluster-proportional-autoscaler',
  'cpa/cluster-proportional-autoscaler-amd64',
  'cpa/cluster-proportional-autoscaler-arm',
  'cpa/cluster-proportional-autoscaler-arm64',
  'cpa/cluster-proportional-autoscaler-ppc64le',
  'cpa/cpvpa',
  'cpa/cpvpa-amd64',
  'cpa/cpvpa-arm',
  'cpa/cpvpa-arm64',
  'cpa/cpvpa-ppc64le',
  'cpvpa-amd64',
  'csi-secrets-store/driver',
  'csi-secrets-store/driver-crds',
  'csi/csi-attacher',
  'csi/csi-node-driver-registrar',
  'csi/csi-provisioner',
  'csi/csi-resizer',
  'csi/csi-snapshotter',
  'csi/livenessprobe',
  'csi/mock-driver',
  'cuda-vector-add',
  'custom-metrics-stackdriver-adapter',
  'debian-base',
  'debian-base-amd64',
  'debian-base-arm',
  'debian-base-arm64',
  'debian-base-ppc64le',
  'debian-base-s390x',
  'debian-hyperkube-base',
  'debian-hyperkube-base-amd64',
  'debian-hyperkube-base-arm',
  'debian-hyperkube-base-arm64',
  'debian-hyperkube-base-ppc64le',
  'debian-hyperkube-base-s390x',
  'debian-iptables',
  'debian-iptables-amd64',
  'debian-iptables-arm',
  'debian-iptables-arm64',
  'debian-iptables-ppc64le',
  'debian-iptables-s390x',
  'defaultbackend',
  'defaultbackend-amd64',
  'defaultbackend-arm',
  'defaultbackend-arm64',
  'defaultbackend-ppc64le',
  'defaultbackend-s390x',
  'descheduler/descheduler',
  'device-plugin-gpu',
  'dns-pod-autoscaler',
  'dns-rc-autoscaler',
  'dns/k8s-dns-dnsmasq-nanny',
  'dns/k8s-dns-dnsmasq-nanny-amd64',
  'dns/k8s-dns-dnsmasq-nanny-arm',
  'dns/k8s-dns-dnsmasq-nanny-arm64',
  'dns/k8s-dns-dnsmasq-nanny-ppc64le',
  'dns/k8s-dns-dnsmasq-nanny-s390x',
  'dns/k8s-dns-kube-dns',
  'dns/k8s-dns-kube-dns-amd64',
  'dns/k8s-dns-kube-dns-arm',
  'dns/k8s-dns-kube-dns-arm64',
  'dns/k8s-dns-kube-dns-ppc64le',
  'dns/k8s-dns-kube-dns-s390x',
  'dns/k8s-dns-node-cache',
  'dns/k8s-dns-node-cache-amd64',
  'dns/k8s-dns-node-cache-arm',
  'dns/k8s-dns-node-cache-arm64',
  'dns/k8s-dns-node-cache-ppc64le',
  'dns/k8s-dns-node-cache-s390x',
  'dns/k8s-dns-sidecar',
  'dns/k8s-dns-sidecar-amd64',
  'dns/k8s-dns-sidecar-arm',
  'dns/k8s-dns-sidecar-arm64',
  'dns/k8s-dns-sidecar-ppc64le',
  'dns/k8s-dns-sidecar-s390x',
  'dnsmasq',
  'dnsmasq-amd64',
  'dnsmasq-metrics-amd64',
  'dnsmasq-metrics-arm',
  'dnsmasq-metrics-arm64',
  'dnsmasq-metrics-ppc64le',
  'dnsutils',
  'e2e-net-amd64',
  'e2e-test-images/agnhost',
  'e2e-test-images/apparmor-loader',
  'e2e-test-images/busybox',
  'e2e-test-images/cuda-vector-add',
  'e2e-test-images/echoserver',
  'e2e-test-images/glusterdynamic-provisioner',
  'e2e-test-images/httpd',
  'e2e-test-images/ipc-utils',
  'e2e-test-images/jessie-dnsutils',
  'e2e-test-images/kitten',
  'e2e-test-images/metadata-concealment',
  'e2e-test-images/nautilus',
  'e2e-test-images/nginx',
  'e2e-test-images/node-perf/npb-ep',
  'e2e-test-images/node-perf/npb-is',
  'e2e-test-images/node-perf/tf-wide-deep',
  'e2e-test-images/nonewprivs',
  'e2e-test-images/nonroot',
  'e2e-test-images/perl',
  'e2e-test-images/pets/peer-finder',
  'e2e-test-images/pets/redis-installer',
  'e2e-test-images/pets/zookeeper-installer',
  'e2e-test-images/redis',
  'e2e-test-images/regression-issue-74839',
  'e2e-test-images/resource-consumer',
  'e2e-test-images/sample-apiserver',
  'e2e-test-images/sample-device-plugin',
  'e2e-test-images/volume/gluster',
  'e2e-test-images/volume/iscsi',
  'e2e-test-images/volume/nfs',
  'e2e-test-images/volume/rbd',
  'echoserver',
  'echoserver-amd64',
  'echoserver-arm',
  'echoserver-ppc64le',
  'elasticsearch',
  'eptest',
  'etcd',
  'etcd-amd64',
  'etcd-arm',
  'etcd-arm64',
  'etcd-empty-dir-cleanup',
  'etcd-ppc64le',
  'etcd-s390x',
  'etcd-statefulset-e2e-test',
  'etcd-version-monitor',
  'etcd-version-monitor-shyamjvs',
  'etcd/etcd',
  'etcd/etcd-empty-dir-cleanup',
  'etcd_monitor_shyamjvs',
  'etcd_probe_shyamjvs',
  'etcd_version_monitor',
  'etcd_version_monitor_shyamjvs',
  'etcdadm/etcd-backup',
  'etcdadm/etcd-dump',
  'etcdadm/etcd-manager',
  'etcdadm/etcd-manager-slim',
  'event-exporter',
  'example-dns-backend',
  'example-dns-frontend',
  'example-guestbook-php-redis',
  'exechealthz',
  'exechealthz-amd64',
  'exechealthz-arm',
  'exechealthz-arm64',
  'exechealthz-ppc64le',
  'exechealthz-s390x',
  'experimental/conformance',
  'experimental/conformance-amd64',
  'experimental/conformance-arm',
  'experimental/conformance-arm64',
  'experimental/conformance-ppc64le',
  'experimental/conformance-s390x',
  'experimental/kube-apiserver',
  'experimental/kube-apiserver-amd64',
  'experimental/kube-apiserver-arm',
  'experimental/kube-apiserver-arm64',
  'experimental/kube-apiserver-ppc64le',
  'experimental/kube-apiserver-s390x',
  'experimental/kube-scheduler-arm',
  'experimental/kube-scheduler-arm64',
  'experimental/kube-scheduler-ppc64le',
  'experimental/kube-scheduler-s390x',
  'explorer',
  'external-dns/external-dns',
  'fakegitserver',
  'federation-apiserver',
  'federation-apiserver-amd64',
  'federation-apiserver-arm',
  'federation-apiserver-arm64',
  'federation-apiserver-ppc64le',
  'federation-controller-manager',
  'federation-controller-manager-amd64',
  'federation-controller-manager-arm',
  'federation-controller-manager-arm64',
  'federation-controller-manager-ppc64le',
  'fetcher',
  'flannel-amd64',
  'flannel-arm',
  'flannel-arm64',
  'flannel-ppc64le',
  'flannel-server-helper',
  'fluent-bit-sd',
  'fluentd-elasticsearch',
  'fluentd-gcp',
  'fluentd-gcp-scaler',
  'fluentd-journal-gcp',
  'fluentd-sidecar-es',
  'fluentd-sidecar-gcp',
  'galera-install',
  'gci-mounter',
  'gcp-controller-manager',
  'gcsweb',
  'gcsweb-amd64',
  'gen-swagger-docs',
  'git-sync',
  'git-sync-amd64',
  'git-sync/git-sync',
  'github-fetcher',
  'github-token-counter',
  'github-transform',
  'gitolite-http',
  'gke-certificates-controller',
  'gke-cloud-kms-plugin',
  'gke-cloud-kms-sync',
  'gke-launcher',
  'gke-master-backup',
  'gke-metadata-server',
  'gke-mpi-api-server',
  'gke-mpi-metadata-server',
  'gke-node-termination-handler',
  'glbc',
  'gmsa-webhook/k8s-gmsa-webhook',
  'google-containers-test-image',
  'goproxy',
  'guestbook',
  'gvisor-admission-webhook-amd64',
  'haproxy',
  'healthz-server',
  'heapster',
  'heapster-amd64',
  'heapster-arm',
  'heapster-arm64',
  'heapster-grafana',
  'heapster-grafana-amd64',
  'heapster-grafana-arm',
  'heapster-grafana-arm64',
  'heapster-grafana-ppc64le',
  'heapster-grafana-s390x',
  'heapster-influxdb',
  'heapster-influxdb-amd64',
  'heapster-influxdb-arm',
  'heapster-influxdb-arm64',
  'heapster-influxdb-ppc64le',
  'heapster-influxdb-s390x',
  'heapster-ppc64le',
  'heapster-s390x',
  'heapster_grafana',
  'heapster_influxdb',
  'hostexec',
  'hpa-example',
  'hpa-example2',
  'hugo',
  'hyperkube',
  'hyperkube-amd64',
  'hyperkube-arm',
  'hyperkube-arm64',
  'hyperkube-ppc64le',
  'hyperkube-s390x',
  'infra-tools/archeio',
  'infra-tools/octodns',
  'ingress-gce-404-server-with-metrics-amd64',
  'ingress-gce-glbc-amd64',
  'ingress-nginx/controller',
  'ingress-nginx/controller-chroot',
  'ingress-nginx/e2e-test-cfssl',
  'ingress-nginx/e2e-test-echo',
  'ingress-nginx/e2e-test-fastcgi-helloserver',
  'ingress-nginx/e2e-test-httpbin',
  'ingress-nginx/e2e-test-runner',
  'ingress-nginx/kube-webhook-certgen',
  'ingress-nginx/nginx',
  'ingress-nginx/nginx-errors',
  'ingress-nginx/opentelemetry',
  'ingressconformance/echoserver',
  'ip-masq-agent',
  'ip-masq-agent-amd64',
  'ip-masq-agent-arm',
  'ip-masq-agent-arm64',
  'ip-masq-agent-ppc64le',
  'iperf',
  'jessie-dnsutils',
  'jsandtest',
  'k8s-cloud-kms-plugin',
  'k8s-custom-iptables',
  'k8s-dns-dnsmasq-amd64',
  'k8s-dns-dnsmasq-arm',
  'k8s-dns-dnsmasq-arm64',
  'k8s-dns-dnsmasq-nanny',
  'k8s-dns-dnsmasq-nanny-amd64',
  'k8s-dns-dnsmasq-nanny-arm',
  'k8s-dns-dnsmasq-nanny-arm64',
  'k8s-dns-dnsmasq-nanny-ppc64le',
  'k8s-dns-dnsmasq-nanny-s390x',
  'k8s-dns-dnsmasq-ppc64le',
  'k8s-dns-dnsmasq-s390x',
  'k8s-dns-e2e-amd64',
  'k8s-dns-e2e-arm',
  'k8s-dns-e2e-arm64',
  'k8s-dns-e2e-ppc64le',
  'k8s-dns-ginkgo-amd64',
  'k8s-dns-ginkgo-arm',
  'k8s-dns-ginkgo-arm64',
  'k8s-dns-ginkgo-ppc64le',
  'k8s-dns-kube-dns',
  'k8s-dns-kube-dns-amd64',
  'k8s-dns-kube-dns-arm',
  'k8s-dns-kube-dns-arm64',
  'k8s-dns-kube-dns-ppc64le',
  'k8s-dns-kube-dns-s390x',
  'k8s-dns-node-cache',
  'k8s-dns-node-cache-amd64',
  'k8s-dns-node-cache-arm',
  'k8s-dns-node-cache-arm64',
  'k8s-dns-node-cache-ppc64le',
  'k8s-dns-node-cache-s390x',
  'k8s-dns-sidecar',
  'k8s-dns-sidecar-amd64',
  'k8s-dns-sidecar-arm',
  'k8s-dns-sidecar-arm64',
  'k8s-dns-sidecar-e2e-amd64',
  'k8s-dns-sidecar-e2e-arm',
  'k8s-dns-sidecar-e2e-arm64',
  'k8s-dns-sidecar-e2e-ppc64le',
  'k8s-dns-sidecar-ppc64le',
  'k8s-dns-sidecar-s390x',
  'k8s-jupyterhub',
  'k8s-tpu-operator',
  'kas-network-proxy/proxy-agent',
  'kas-network-proxy/proxy-server',
  'kibana',
  'kops/dns-controller',
  'kops/dns-controller-amd64',
  'kops/dns-controller-arm64',
  'kops/kops-controller',
  'kops/kops-controller-amd64',
  'kops/kops-controller-arm64',
  'kops/kube-apiserver-healthcheck',
  'kops/kube-apiserver-healthcheck-amd64',
  'kops/kube-apiserver-healthcheck-arm64',
  'kube-addon-manager',
  'kube-addon-manager-amd64',
  'kube-addon-manager-arm',
  'kube-addon-manager-arm64',
  'kube-addon-manager-ppc64le',
  'kube-addon-manager-s390x',
  'kube-aggregator',
  'kube-aggregator-amd64',
  'kube-aggregator-arm',
  'kube-aggregator-arm64',
  'kube-aggregator-ppc64le',
  'kube-aggregator-s390x',
  'kube-apiserver',
  'kube-apiserver-amd64',
  'kube-apiserver-arm',
  'kube-apiserver-arm64',
  'kube-apiserver-ppc64le',
  'kube-apiserver-s390x',
  'kube-controller-manager',
  'kube-controller-manager-amd64',
  'kube-controller-manager-arm',
  'kube-controller-manager-arm64',
  'kube-controller-manager-ppc64le',
  'kube-controller-manager-s390x',
  'kube-cross',
  'kube-discovery-amd64',
  'kube-discovery-arm',
  'kube-discovery-arm64',
  'kube-dns-perf-client-amd64',
  'kube-dnsmasq-amd64',
  'kube-dnsmasq-arm',
  'kube-dnsmasq-arm64',
  'kube-dnsmasq-ppc64le',
  'kube-haproxy',
  'kube-keepalived-vip',
  'kube-nethealth-amd64',
  'kube-proxy',
  'kube-proxy-amd64',
  'kube-proxy-arm',
  'kube-proxy-arm64',
  'kube-proxy-ppc64le',
  'kube-proxy-s390x',
  'kube-registry-proxy',
  'kube-scheduler',
  'kube-scheduler-amd64',
  'kube-scheduler-arm',
  'kube-scheduler-arm64',
  'kube-scheduler-ppc64le',
  'kube-scheduler-s390x',
  'kube-state-metrics',
  'kube-state-metrics-amd64',
  'kube-state-metrics-arm',
  'kube-state-metrics-arm64',
  'kube-state-metrics-ppc64le',
  'kube-state-metrics-s390x',
  'kube-state-metrics/kube-state-metrics',
  'kube-state-metrics/kube-state-metrics-amd64',
  'kube-state-metrics/kube-state-metrics-arm',
  'kube-state-metrics/kube-state-metrics-arm64',
  'kube-state-metrics/kube-state-metrics-ppc64le',
  'kube-state-metrics/kube-state-metrics-s390x',
  'kube-ui',
  'kube2sky',
  'kube2sky-amd64',
  'kube2sky-arm',
  'kube2sky-arm64',
  'kube2sky-ppc64le',
  'kubectl',
  'kubedash',
  'kubedns-amd64',
  'kubedns-arm',
  'kubedns-arm64',
  'kubedns-ppc64le',
  'kubekins-e2e',
  'kubekins-job-builder',
  'kubekins-test',
  'kubelet-to-gcm',
  'kubernetes-dashboard',
  'kubernetes-dashboard-amd64',
  'kubernetes-dashboard-arm',
  'kubernetes-dashboard-arm64',
  'kubernetes-dashboard-init-amd64',
  'kubernetes-dashboard-init-arm',
  'kubernetes-dashboard-ppc64le',
  'kubernetes-dashboard-s390x',
  'kubernetes-kafka',
  'kubernetes-zookeeper',
  'kubernetes/conformance',
  'kubernetes/conformance-amd64',
  'kubernetes/conformance-arm',
  'kubernetes/conformance-arm64',
  'kubernetes/conformance-ppc64le',
  'kubernetes/conformance-s390x',
  'kubernetes/etcd',
  'kubernetes/etcd-empty-dir-cleanup',
  'kubernetes/hyperkube',
  'kubernetes/hyperkube-amd64',
  'kubernetes/hyperkube-arm',
  'kubernetes/hyperkube-arm64',
  'kubernetes/hyperkube-ppc64le',
  'kubernetes/hyperkube-s390x',
  'kubernetes/kube-apiserver',
  'kubernetes/kube-apiserver-amd64',
  'kubernetes/kube-apiserver-arm',
  'kubernetes/kube-apiserver-arm64',
  'kubernetes/kube-apiserver-ppc64le',
  'kubernetes/kube-apiserver-s390x',
  'kubernetes/kube-controller-manager',
  'kubernetes/kube-controller-manager-amd64',
  'kubernetes/kube-controller-manager-arm',
  'kubernetes/kube-controller-manager-arm64',
  'kubernetes/kube-controller-manager-ppc64le',
  'kubernetes/kube-controller-manager-s390x',
  'kubernetes/kube-proxy',
  'kubernetes/kube-proxy-amd64',
  'kubernetes/kube-proxy-arm',
  'kubernetes/kube-proxy-arm64',
  'kubernetes/kube-proxy-ppc64le',
  'kubernetes/kube-proxy-s390x',
  'kubernetes/kube-scheduler',
  'kubernetes/kube-scheduler-amd64',
  'kubernetes/kube-scheduler-arm',
  'kubernetes/kube-scheduler-arm64',
  'kubernetes/kube-scheduler-ppc64le',
  'kubernetes/kube-scheduler-s390x',
  'kubernetes/pause',
  'kubernetes/pause-amd64',
  'kubernetes/pause-arm',
  'kubernetes/pause-arm64',
  'kubernetes/pause-ppc64le',
  'kubernetes/pause-s390x',
  'kueue/kueue',
  'kustomize/kustomize',
  'kwok/cluster',
  'kwok/kwok',
  'leader-elector',
  'liveness',
  'loader',
  'logexp',
  'logexporter',
  'logs-generator',
  'managed-certificate-controller',
  'metadata-proxy',
  'metrics-server',
  'metrics-server-amd64',
  'metrics-server-arm',
  'metrics-server-arm64',
  'metrics-server-ppc64le',
  'metrics-server-s390x',
  'metrics-server/metrics-server',
  'metrics-server/metrics-server-amd64',
  'metrics-server/metrics-server-arm',
  'metrics-server/metrics-server-arm64',
  'metrics-server/metrics-server-ppc64le',
  'metrics-server/metrics-server-s390x',
  'minikube-nvidia-driver-installer',
  'mongodb-install',
  'mounttest',
  'mounttest-user',
  'multitenancy/externalip-webhook',
  'mungegithub',
  'mysql-galera',
  'mysql-healthz',
  'n-way-http',
  'netd',
  'netd-amd64',
  'netexec',
  'netproxy',
  'nettest',
  'networking/ingress-gce-404-server-with-metrics-amd64',
  'networking/ip-masq-agent',
  'networking/ip-masq-agent-amd64',
  'networking/ip-masq-agent-arm',
  'networking/ip-masq-agent-arm64',
  'networking/ip-masq-agent-ppc64le',
  'nfd/node-feature-discovery',
  'nfd/node-feature-discovery-operator',
  'nginx',
  'nginx-ingress',
  'nginx-ingress-controller',
  'nginx-ingress-controller-amd64',
  'nginx-ingress-controller-arm',
  'nginx-ingress-controller-arm64',
  'nginx-ingress-controller-ppc64le',
  'nginx-scale',
  'nginx-slim',
  'nginx-slim-amd64',
  'nginx-slim-arm',
  'nginx-slim-arm64',
  'nginx-slim-ppc64le',
  'nginx-third-party',
  'no-snat-test-amd64',
  'no-snat-test-proxy-amd64',
  'node-conformance',
  'node-perf-dash',
  'node-problem-detector',
  'node-problem-detector/node-problem-detector',
  'node-test',
  'node-test-amd64',
  'node-test-arm',
  'node-test-arm64',
  'nodejs-election-client',
  'non-masquerade-daemon-amd64',
  'nonewprivs',
  'nvidia-gpu-device-plugin',
  'pause',
  'pause-amd64',
  'pause-arm',
  'pause-arm64',
  'pause-ppc64le',
  'pause-s390x',
  'peer-finder',
  'perfdash',
  'podmaster',
  'porter',
  'portforwardtester',
  'prometheus-adapter/prometheus-adapter',
  'prometheus-dummy-exporter',
  'prometheus-to-sd',
  'provider-aws/aws-ebs-csi-driver',
  'provider-aws/cloud-controller-manager',
  'provider-os/barbican-kms-plugin',
  'provider-os/cinder-csi-plugin',
  'provider-os/k8s-keystone-auth',
  'provider-os/magnum-auto-healer',
  'provider-os/manila-csi-plugin',
  'provider-os/octavia-ingress-controller',
  'provider-os/openstack-cloud-controller-manager',
  'proxy-agent',
  'proxy-server',
  'proxy-to-service',
  'publisher',
  'publishing-bot/k8s-publishing-bot',
  'python',
  'queue-health-base',
  'queue-health-graph',
  'queue-health-poll',
  'redis',
  'redis-install',
  'redis-install-3.2.0',
  'redis-slave',
  'registry-promoter-test-image',
  'releng/kubepkg',
  'releng/kubepkg-rpm',
  'releng/releng-ci',
  'rescheduler',
  'rescheduler-amd64',
  'rescheduler-arm',
  'rescheduler-arm64',
  'rescheduler-ppc64le',
  'rescheduler-s390x',
  'resource_consumer',
  'resource_consumer/controller',
  'rethinkdb',
  'scheduler-plugins/controller',
  'scheduler-plugins/kube-scheduler',
  'scl-image-builder/cluster-node-image-builder-amd64',
  'sd-dummy-exporter',
  'seccomp-operator/seccomp-operator',
  'security-profiles-operator-bundle/security-profiles-operator',
  'security-profiles-operator-bundle/security-profiles-operator-amd64',
  'security-profiles-operator-bundle/security-profiles-operator-arm64',
  'security-profiles-operator-bundle/security-profiles-operator-bundle',
  'security-profiles-operator-bundle/security-profiles-operator-catalog',
  'security-profiles-operator-catalog/security-profiles-operator',
  'security-profiles-operator-catalog/security-profiles-operator-amd64',
  'security-profiles-operator-catalog/security-profiles-operator-arm64',
  'security-profiles-operator-catalog/security-profiles-operator-bundle',
  'security-profiles-operator-catalog/security-profiles-operator-catalog',
  'security-profiles-operator/security-profiles-operator',
  'security-profiles-operator/security-profiles-operator-amd64',
  'security-profiles-operator/security-profiles-operator-arm64',
  'security-profiles-operator/security-profiles-operator-bundle',
  'security-profiles-operator/security-profiles-operator-catalog',
  'serve-hostname-amd64',
  'serve-hostname-arm',
  'serve-hostname-arm64',
  'serve-hostname-ppc64le',
  'serve-hostname-s390x',
  'serve_hostname',
  'serve_hostname-amd64',
  'serve_hostname-arm',
  'serve_hostname-arm64',
  'serve_hostname-ppc64le',
  'serve_hostname-s390x',
  'servicelb',
  'shame-mailer',
  'shyamjvs-logexp',
  'shyamjvs-prometheus-to-sd',
  'sig-auth/pod-security-webhook',
  'sig-storage/csi-attacher',
  'sig-storage/csi-external-health-monitor-agent',
  'sig-storage/csi-external-health-monitor-controller',
  'sig-storage/csi-node-driver-registrar',
  'sig-storage/csi-provisioner',
  'sig-storage/csi-resizer',
  'sig-storage/csi-snapshotter',
  'sig-storage/hello-populator',
  'sig-storage/hostpathplugin',
  'sig-storage/iscsiplugin',
  'sig-storage/livenessprobe',
  'sig-storage/local-volume-provisioner',
  'sig-storage/mock-driver',
  'sig-storage/nfs-provisioner',
  'sig-storage/nfs-subdir-external-provisioner',
  'sig-storage/nfsplugin',
  'sig-storage/smbplugin',
  'sig-storage/snapshot-controller',
  'sig-storage/snapshot-validation-webhook',
  'sig-storage/volume-data-source-validator',
  'skydns',
  'skydns-amd64',
  'skydns-arm',
  'skydns-arm64',
  'skydns-ppc64le',
  'slack-infra/slack-event-log',
  'slack-infra/slack-moderator',
  'slack-infra/slack-report-message',
  'slack-infra/slack-welcomer',
  'slack-infra/tempelis',
  'slo-monitor',
  'spark',
  'spark-base',
  'spark-driver',
  'spark-master',
  'spark-worker',
  'spartakus-amd64',
  'startup-script',
  'storage-migrator/storage-version-migration-initializer',
  'storage-migrator/storage-version-migration-migrator',
  'storage-migrator/storage-version-migration-trigger',
  'storage/csi-attacher',
  'storage/csi-node-driver-registrar',
  'storage/csi-provisioner',
  'storage/csi-resizer',
  'storage/csi-snapshotter',
  'storage/livenessprobe',
  'storage/mock-driver',
  'stress',
  'submit-queue',
  'tensorflow-gpu-notebook',
  'test-webserver',
  'test_subdir_1/test_subdir_2/test_image',
  'tf-models',
  'tiny-glibc-amd64',
  'tiny-glibc-arm',
  'tiny-glibc-arm64',
  'tiny-glibc-ppc64le',
  'toolbox',
  'ubuntu',
  'ubuntu-nvidia-driver-installer',
  'ubuntu-slim',
  'ubuntu-slim-amd64',
  'ubuntu-slim-arm',
  'ubuntu-slim-arm64',
  'ubuntu-slim-ppc64le',
  'update-demo',
  'visio-stencil-creator',
  'volume-ceph',
  'volume-csi/compute-persistent-disk-csi-driver',
  'volume-csi/gcp-compute-persistent-disk-csi-driver',
  'volume-csi/gcp-filestore-csi-driver',
  'volume-gluster',
  'volume-iscsi',
  'volume-nfs',
  'volume-rbd',
  'vpa-admission-controller',
  'vpa-recommender',
  'vpa-updater',
  'watcher-daemonset',
  'webhooks-publisher',
  'zeppelin',
  'zeppelin-proxy',
  'zookeeper-install',
  'zookeeper-install-3.5.0-alpha',
];

const k8Registry: PresetTemplate = {
  description:
    'The Kubernetes container registry has changed from `k8s.gcr.io` to `registry.k8s.io`.',
  packageRules: [
    {
      matchDatasources: ['docker'],
      replacements: k8sImages.map((k8sImage) => [
        [`k8s.gcr.io/${k8sImage}`],
        `registry.k8s.io/${k8sImage}`,
      ]),
    },
  ],
  title: 'k8s-registry-move',
};

const messageFormat: PresetTemplate = {
  description:
    'The `messageformat` monorepo package naming scheme changed from `messageFormat-{{package}}`-to-`@messageformat/{{package}}`.',
  packageRules: [
    {
      matchCurrentVersion: '>=2.0.0 <3.0.0',
      matchDatasources: ['npm'],
      replacements: [
        [['messageformat-cli'], '@messageformat/cli'],
        [['messageformat'], '@messageformat/core'],
      ],
      replacementVersion: '3.0.0',
    },
    {
      matchCurrentVersion: '>=0.4.0 <1.0.0',
      matchDatasources: ['npm'],
      replacements: [
        [['messageformat-convert'], '@messageformat/convert'],
        [['react-message-context'], '@messageformat/react'],
      ],
      replacementVersion: '1.0.0',
    },
    {
      matchCurrentVersion: '>=4.0.0 <5.0.0',
      matchDatasources: ['npm'],
      replacements: [[['messageformat-parser'], '@messageformat/parser']],
      replacementVersion: '5.0.0',
    },
  ],
  title: 'messageFormat-{{package}}-to-@messageformat/{{package}}',
};

addPresets(presets, messageFormat, mui, k8Registry);
