# based on https://github.com/PierreRAFFA/cancel-previous-runs-action/blob/main/.github/workflows/test.yaml
name: Cancel stale merge queue workflows
on:
  pull_request:
  merge_group:
    types:
      - checks_requested

permissions:
  actions: write
  contents: read

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: pierreraffa/cancel-previous-runs-action@133ec2d94c3dfeb83959ffc3c73640633044bd89 # 1.11
        with:
          workflow_names: '*'
