name: Close answered discussions

permissions:
  discussions: write

on:
  # run daily
  schedule:
    - cron: '0 0 * * *'

  # allow manual trigger
  workflow_dispatch:

jobs:
  close-answered-discussions:
    runs-on: ubuntu-latest
    if: github.repository == 'renovatebot/renovate'

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          show-progress: false

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('.github/workflows/close-answered-discussions/script.cjs')
            console.log(await script({github, context, discussionAnsweredDays: 30}))
