name: Close answered discussions

permissions:
  discussions: write

on:
  # run daily
  schedule:
    - cron: '0 0 * * *'

  # allow manual trigger
  workflow_dispatch:

jobs:
  close-answered-discussions:
    runs-on: ubuntu-latest
    if: github.repository == 'renovatebot/renovate'

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          show-progress: false

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('.github/workflows/close-answered-discussions/script.cjs')
            console.log(await script({github, context, discussionAnsweredDays: 30}))
