name: Devcontainer
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  devcontainer-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - name: Build and run dev container task
        uses: devcontainers/ci@19ddf8c5778961129f90613da69436820ba5e0d9 # v0.3.1900000448
        with:
          runCmd: pnpm build
