name: 'Find issues with missing labels'

on:
  schedule:
    # Run every Sunday at midnight
    - cron: '0 0 * * 0'
  # Or when manually requested
  workflow_dispatch: {}

permissions: {}

jobs:
  check-unlabeled-issues:
    runs-on: ubuntu-latest
    if: github.repository == 'renovatebot/renovate'

    permissions:
      issues: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Search for issues with missing labels
        run: bash ./tools/find-issues-with-missing-labels.sh
