name: 'Merge main into PR branch'

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-main:
    if: >-
      github.repository == 'renovatebot/renovate' &&
      github.event.label.name == 'auto:pls-merge-main' &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: 'auto:pls-merge-main',
            });

            await github.rest.pulls.updateBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
