name: 'Update static data'
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

env:
  NODE_VERSION: 24

permissions: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    if: github.repository == 'renovatebot/renovate'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          show-progress: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          standalone: true

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install mise
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          # don't run `mise install`, but do install a version of `mise` itself
          install: false

      - name: Update static data
        run: pnpm run update-static-data

      - name: Run Prettier
        run: pnpm prettier-fix

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: 'chore/update-static-data'
          commit-message: 'feat(data): automatic update of static data'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          title: 'feat(data): automatic update of static data'
          assignees: viceice,secustor,jamietanna
