name: 'Update static data'
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

env:
  NODE_VERSION: 24

permissions: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    if: github.repository == 'renovatebot/renovate'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          show-progress: false

      - name: Setup pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          install: false
          runtime: node@${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install mise
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
        with:
          # don't run `mise install`, but do install a version of `mise` itself
          install: false

      - name: Update static data
        run: pnpm run update-static-data

      - name: Run Prettier
        run: pnpm prettier-fix

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: 'chore/update-static-data'
          commit-message: 'feat(data): automatic update of static data'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          title: 'feat(data): automatic update of static data'
          assignees: viceice,secustor,jamietanna
